import 'dotenv/config';

export class GeminiProvider {
  private readonly apiKey = process.env.GEMINI_API_KEY || process.env.GOOGLE_API_KEY;
  private readonly model = process.env.AI_MODEL || 'gemini-2.5-flash';
  private aiClient?: any;

  async generate(prompt: string, responseSchema?: any): Promise<string> {
    if (!this.apiKey) {
      throw new Error('Gemini API key is not configured.');
    }
    if (!this.aiClient) {
      const { GoogleGenAI } = await import('@google/genai');
      this.aiClient = new GoogleGenAI({ apiKey: this.apiKey });
    }

    const config: any = {};
    if (responseSchema) {
      config.responseMimeType = 'application/json';
      config.responseSchema = responseSchema;
    }

    const response = await this.aiClient.models.generateContent({
      model: this.model,
      contents: prompt,
      config,
    });

    const text = response.text;
    if (!text) {
      throw new Error('No content generated by Gemini.');
    }
    return text;
  }
}
